{{- if (include "redpanda.semver" . | semverCompare ">=22.1.1") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "redpanda.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common-labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/name: {{ template "redpanda.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/component: {{ template "redpanda.name" . }}
{{- with .Values.commonLabels }}
  {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "redpanda.name" . }}-post-upgrade
        image: {{ .Values.image.repository}}:{{ template "redpanda.tag" . }}
        command: ["/bin/sh", "-c"]
        args:
          - /mnt/scripts/post-upgrade.sh
        env:
          - name: RP_API_URLS
            value: {{ template "redpanda.fullname" . }}-0.{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.admin.port }}
          - name: RP_ADMIN_TLS_ENABLED
            value: {{ include "admin-internal-tls-enabled" . }}
          - name: RP_ADMIN_TLS_CERT
            value: {{ .Values.listeners.admin.tls.cert }}
          - name: RP_KAFKA_TLS_ENABLED
            value: {{ include "kafka-internal-tls-enabled" . }}
          - name: RP_KAFKA_TLS_CERT
            value: {{ .Values.listeners.kafka.tls.cert }}
          - name: RP_SASL_ENABLED
            value: {{ include "sasl-enabled" . }}
        {{- if .Values.auth.enabled }}
        envFrom:
          - secretRef:
              name: {{ .Values.auth.bootstrap.secretName | default (include "redpanda.bootstrap-secret-name" .) }}
        {{- end }}
        volumeMounts:
          - name: {{ template "redpanda.fullname" . }}
            mountPath: /tmp/base-config
          - name: config
            mountPath: /etc/redpanda
          - name: post-upgrade-script
            mountPath: /mnt/scripts
{{- if (include "tls-enabled" . | fromJson).bool }}
  {{- range $name, $cert := .Values.tls.certs }}
          - name: redpanda-{{ $name }}-cert
            mountPath: {{ printf "/etc/tls/certs/%s" $name }}
  {{- end }}
{{- end }}
      volumes:
        - name: {{ template "redpanda.fullname" . }}
          configMap:
            name: {{ template "redpanda.fullname" . }}
        - name: post-upgrade-script
          configMap:
            name: {{ include "redpanda.fullname" . }}-post-upgrade
            defaultMode: 0544
        - name: config
          emptyDir: {}
{{- if (include "tls-enabled" . | fromJson).bool }}
  {{- range $name, $cert := .Values.tls.certs }}
        - name: redpanda-{{ $name }}-cert
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
    {{- if $cert.caEnabled }}
            - key: ca.crt
              path: ca.crt
    {{- end }}
            secretName: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert
  {{- end }}
{{- end -}}
{{- end }}
